# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       xtail

# >> macros
# << macros

Summary:    a multi-file tail(1)
Version:    2.1
Release:    0
Group:      Applications/System
License:    BSD
URL:        https://unicom.crosenthal.com/sw/xtail
Source0:    %{name}-%{version}.tar.gz
Source100:  xtail.yaml
Patch0:     0001-Use-ISO8601-Fix-Gcc-header-Use-C-c.patch
Patch1:     0001-xtail.1-remove-SIGQUIT.patch
Patch2:     xtail_2.1-5-debian-local-changes.patch
BuildRequires:  autoconf
BuildRequires:  automake

%description
xtail watches the growth of files.

It's like running a "tail -f" on a bunch of files at once.

You can specify both filenames and directories on the command line.

If you specify a directory, it watches all the files in that directory.  It
will notice when new files are created (and start watching them) or when old
files are deleted (and stop watching them).

=== HISTORICAL NOTES ===

This program is an oldie but goodie.  It was posted to comp.sources.misc
in July 1989 (see ftp.uu.net:/usenet/comp.sources.misc/volume7/xtail.Z).
I remember posting an even earlier version to alt.sources.  It has been
published in the O'Reilly & Associates "Unix Power Tools" collection
(book and CD-ROM).

Over the years, some fly-by-night organizations (such as the MIT X
Consortium and SGI) have tried to steal the "xtail" name.  Don't be
fooled!  Insist on the original.

The 1989 release credited David Dykstra for his contributions.

Chip Rosenthal
<chip@unicom.com>

%if "%{?vendor}" == "chum"
PackageName: xtail
Type: console-application
DeveloperName: Chip Rosenthal
PackagerName: nephros
Categories:
  - System
  - Utility
Custom:
  PackagingRepo: https://github.com/sailfishos-chum/detox
Url:
  Homepage: https://unicom.crosenthal.com/sw/xtail
%endif


%package docs
Summary:    Documentation files for %{name}
Group:      Documentation
BuildArch:  noarch
AutoReq:    0
Requires:   %{name} = %{version}-%{release}

%description docs
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# 0001-Use-ISO8601-Fix-Gcc-header-Use-C-c.patch
%patch0 -p1
# 0001-xtail.1-remove-SIGQUIT.patch
%patch1 -p1
# xtail_2.1-5-debian-local-changes.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static

# >> build post
%{__make}
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
%{__install} -D -m 755 xtail $RPM_BUILD_ROOT%{_bindir}/xtail
%{__install} -D -m 644 xtail.1 $RPM_BUILD_ROOT%{_mandir}/xtail.1
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
# >> files
# << files

%files docs
%defattr(-,root,root,-)
%{_mandir}/*
# >> files docs
# << files docs
